### ISSUE TITLE
create mobile frontend

### ISSUE THREAD

**Issue by takacs** [takacs/trashman#1]
How, using what technology, and what views to have is still up for debate but here's the basic structure I'm imagining currently for this app (the images are for some visual guidance they are nowhere near intended to be final designs that can be decided down the line, the focus here is the functionality):

#### Map view

Displays the map and all the trash reported in the area. Ideally pins could be clickable to display an image and information about the trash reported.

<img width="380" alt="Screenshot 2024-07-26 at 00 31 21" src="https://github.com/user-attachments/assets/b76e6132-a824-4ff5-b190-79ea8be6fff1">

#### List view

Displays list of trash and how far it is from current location. Could have other options for sorting and additionally filtering.

<img width="380" alt="Screenshot 2024-07-26 at 00 33 16" src="https://github.com/user-attachments/assets/d3769e48-7bfe-43f6-b31b-4c8c91cc68c0">

#### User view

Information about user displaying how many trash they have reported and cleaned. (probably not necessary for initial version)

<img width="378" alt="Screenshot 2024-07-26 at 00 34 21" src="https://github.com/user-attachments/assets/10b95fe2-a2c9-4b41-b2b5-b3200e3b4dae">

#### TODOs
- [x] create https://reactnative.dev app
- [ ] create map view (this [video](https://www.youtube.com/watch?v=_IyWSsFXLcA) seems like a good place to start)
- [ ] create list view
- [ ] create getting-started docs explaining how to setup and run on any machine

**Comment by panko** [comment]
- [x]   install android studio and react native
